Реализация односвязного спискa Kotlin
SlavaKalkaev/StudyJava pull request #31
Opened 2024-01-18 20:45 UTC by SlavaKalkaev

2024-01-19 17:20 UTC, DionisSerbin commented on src/linkedlist/KLinkedListImpl.kt
> +    constructor() {
я так понимаю что здесь вообще конструктор не нужен

2024-01-19 17:21 UTC, DionisSerbin commented on src/linkedlist/KLinkedListImpl.kt
> +class KLinkedListImpl<T : Any> : LinkedListInterface<T> {
убери Any, оно тут не нужно

2024-01-19 17:22 UTC, DionisSerbin commented on src/linkedlist/KLinkedListImpl.kt
> +        val node = NodeLL(data)
здесь желательно написать наверное Node<T>

2024-01-19 17:22 UTC, DionisSerbin commented on src/linkedlist/KLinkedListImpl.kt
> +            currentNode = currentNode?.next as NodeLL<T>?
Зачем as ? Можно по идее без него работать

2024-01-19 17:23 UTC, DionisSerbin commented on src/linkedlist/KLinkedListImpl.kt
> +            currentNode = currentNode?.next as NodeLL<T>?
Был прекрасно забит хуй на исходный код программы, нет цикла)

2024-01-19 17:25 UTC, DionisSerbin commented on src/linkedlist/KLinkedListImpl.kt
> +            currentNode = currentNode?.next as NodeLL<T>?
там кстати почему-то(схуято) в оригинальном коде while (head.getNext() != null) { ... Хотя должен быть current.next. Исправь и там и тут

2024-01-19 17:26 UTC, DionisSerbin commented on src/linkedlist/KLinkedListImpl.kt
> +    override fun size(): Int {
в целом можно не создавать этот метод, а просто сделать size публичным полем, и в коде можно не писать this.size, а просто size

2024-01-19 17:27 UTC, DionisSerbin commented on src/linkedlist/KLinkedListImpl.kt
> +        var node = NodeLL(data)
сейм

2024-01-19 17:28 UTC, DionisSerbin commented on src/linkedlist/KLinkedListImpl.kt
> +                for (i in 0..(index - 1)) {
здесь можно без скобок написать index - 1

2024-01-19 17:28 UTC, DionisSerbin commented on src/linkedlist/KLinkedListImpl.kt
> +                    node = node.next as NodeLL<T>
сейм

2024-01-19 17:29 UTC, DionisSerbin commented on src/linkedlist/KLinkedListImpl.kt
> +                if (left != null) {
не понятно зачем проверка

2024-01-19 17:30 UTC, DionisSerbin commented on src/linkedlist/KLinkedListImpl.kt
> +                    node.next = left.next
опять же очень хочется внимательности побольше) Проебал строчку из оригинала

2024-01-19 17:31 UTC, DionisSerbin commented on src/linkedlist/KLinkedListImpl.kt
> +                currentHead = currentHead?.next as NodeLL<T>?
не понимаю почему везде as)

2024-01-19 17:32 UTC, DionisSerbin commented on src/linkedlist/KLinkedListImpl.kt
> +                for (i in 0..(index - 1)) {
сейм

2024-01-19 17:33 UTC, DionisSerbin commented on src/linkedlist/KLinkedListImpl.kt
> +                currentNode?.setNext(currentNode.next.next)
поч через setNext? Можно просто было ...next = ...

2024-01-21 16:11 UTC, SlavaKalkaev commented on src/linkedlist/KLinkedListImpl.kt
> +        val node = NodeLL(data)
где конкретно?

2024-01-21 16:19 UTC, SlavaKalkaev commented on src/linkedlist/KLinkedListImpl.kt
> +        var node = NodeLL(data)
что сейм

2024-01-21 16:19 UTC, DionisSerbin commented on src/linkedlist/KLinkedListImpl.kt
> +        val node = NodeLL(data)
Скорее всего я имел ввиду вот так:
val node = NodeLL<T>(data)
Либо val node: NodeLL<T> = NodeLL<T>(data)

2024-01-22 14:35 UTC, DionisSerbin requested changes

2024-01-22 14:35 UTC, DionisSerbin commented on src/linkedlist/KLinkedListImpl.kt
> +                currentNode?.next = node
гений, не туда вставил

2024-01-22 14:35 UTC, DionisSerbin commented on src/linkedlist/KLinkedListImpl.kt
> +                currentNode?.setNext(currentNode.next.next)
Так и не исправил

2024-01-22 14:36 UTC, DionisSerbin commented
Где кстати измененные файлы Node и LinkedList обычного?

2024-01-22 14:37 UTC, DionisSerbin commented
Я так понимаю что ты их просто забыл добавить

2024-01-22 14:56 UTC, DionisSerbin approved these changes

2024-01-22 14:57 UTC, merged